# NSTP server configuration
nstp_server:
  port: 22300                   # NSTP server port

# Status server configuration
status_server:
  ipv4_address: "127.0.0.1"   # IPv4 address of the status server
  ipv6_address: "..."           # Or, an IPv6 address
  port: 22301                   # Status server port

# Path to a `CertificateStore`
trusted_certificate_store: "../03-NETSEC-testing/pki/trusted_certs_v2.db"

# Path to a `PinnedCertificateStore`
pinned_certificate_store: "../03-NETSEC-testing/pki/pinned_certs_v2.db"

# Path to the server `Certificate`
server_certificate: "/data/server.crt"

# Path to the server `PrivateKey`
server_private_key: "/data/server.key"

# Valid user credentials
users:
  - name: "root"
    #mypass
    password_hash: "$argon2id$v=19$m=102400,t=2,p=8$AACAUIoxRkhJqXVuLcV4Tw$UJfkjV1zlv+e21A6p+v/8w"
    #password_hash: "$argon2id$v=19$m=102400,t=2,p=8$KaUUwhiDsFaqFYLwXuu91w$mBQqnhGcQpOn04EpsxodDQ"
  - name: "little_mac"
    password_hash: "$argon2id$v=19$m=102400,t=2,p=8$hhACIKS0ltLa23svBYAwRg$bOzZyOZDwtESuivuYLuAxg"
